### ISSUE TITLE
Crashing on Jessie (after 4 or 5 tx times)

### ISSUE THREAD

**Issue by Supremehamster** [JamesP6000/WsprryPi#10]
Problem:
WsprryPi crashing  the Pi2modelB after 4 or 5 times with varying parameters supplied on Jessie.
Cause: 
Crashes only after screen blank.
Solution: 
Setting consoleblank=0 in /boot/cmdline.txt and rebooting fixed it.
Perhaps the wsprrypi code (or lower) can't handle a post-blanked screen?

**Comment by Supremehamster** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=122112
may be of further help

**Comment by JamesP6000** [comment]
Thanks for this. I added it to the README.
