### ISSUE TITLE
Double frequency.

### ISSUE THREAD

**Issue by alfille** [JamesP6000/WsprryPi#7]
When I ran on P1 1B I get a frequency on GP4 that is double the specified (and reported frequency). For instance, trying 20m the frequency should be 14097100+- but is actually 28194200. 
And my TAPR filter filters it out.

When I specify 7048550 (half the frequency) GP4 actually is at 14097100 and the beacon works at 20m.

**Comment by JamesP6000** [comment]
That's very odd... Can you send me the actual command line you used?

James

**Comment by alfille** [comment]
Originally:

ExecStart=wspr -r -s -o  K1PHA FN42 20 20m

(part of a systemd script)

But then to test

wspr -t 14097100

gave a doubled rate on pin 4 (measured with a HP 5432A frequency
counter to the nearest Hz)

and now I use

# Seems to double the frequency
# so use 20 meter 14097100 / 2 = 7048550
ExecStart=/usr/bin/wspr -r -s -o  K1PHA FN42 20 7048550 0 0 0 0

Sucessfully (I added to extra pauses so as not to clutter up the airwaves)

**Comment by JamesP6000** [comment]
I'm still not seeing this behavior... Can someone else confirm this? Are people receiving your transmissions on the double frequency?

JP

**Comment by alfille** [comment]
This is a Pi 1B. And yes, my beacon is seen in Belgium Venezuela Texas (from Boston). (This is set at 7MH read at 14MHz=20m).

It's a standard Raspbian setup, headless.
